<a href="https://colab.research.google.com/github/20pa1a1268/CAP/blob/main/stress.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import VotingClassifier
from sklearn.metrics import confusion_matrix, accuracy_score,  classification_report

In [121]:
df = pd.read_csv('test.csv', encoding='latin-1')
df1 = pd.read_csv('Datasets.csv', encoding='latin-1')
df.shape
df1.shapen

(5017, 22)

In [90]:

df.fillna(value=1,inplace=True)
df.isnull().sum()

MEAN_RR              0
MEDIAN_RR            0
SDRR                 0
RMSSD                0
SDSD                 0
SDRR_RMSSD           0
HR                   0
pNN25                0
pNN50                0
SD1                  0
SD2                  0
KURT                 0
SKEW                 0
MEAN_REL_RR          0
MEDIAN_REL_RR        0
SDRR_REL_RR          0
RMSSD_REL_RR         0
SDSD_REL_RR          0
SDRR_RMSSD_REL_RR    0
KURT_REL_RR          0
SKEW_REL_RR          0
VLF                  0
VLF_PCT              0
LF                   0
LF_PCT               0
LF_NU                0
HF                   0
HF_PCT               0
HF_NU                0
TP                   0
LF_HF                0
HF_LF                0
sampen               0
higuci               0
datasetId            0
condition            0
results              0
dtype: int64

In [ ]:
print(df.columns)
a=list(df["MEAN_RR"])
l1=[]
for i in a:
  l1.append(int(i))
df["MEAN_RR"]=l1

b=list(df["MEDIAN_RR"])
l2=[]
for i in b:
  l2.append(int(i))
df["MEAN_RR"]=l2

c=list(df["SDRR"])
l3=[]
for i in c:
  l3.append(int(i))
df["SDRR"]=l3

d=list(df["RMSSD"])
l4=[]
for i in d:
  l4.append(int(i))
df["RMSSD"]=l4

e=list(df["SDSD"])
l5=[]
for i in e:
  l5.append(int(i))
df["SDSD"]=l5

f=list(df["SDRR_RMSSD"])
l6=[]
for i in f:
  l6.append(int(i))
df["SDRR_RMSSD"]=l6

g=list(df["HR"])
l7=[]
for i in g:
  l7.append(int(i))
df["HR"]=l7

h=list(df["VLF"])
l8=[]
for i in h:
  l8.append(int(i))
df["VLF"]=l8

i1=list(df["VLF_PCT"])
l9=[]
for i in i1:
  l9.append(int(i))
df["VLF_PCT"]=l9

j=list(df["LF"])
l10=[]
for i in j:
  l10.append(int(i))
df["LF"]=l10

k=list(df["LF_PCT"])
l11=[]
for i in k:
  l11.append(int(i))
df["LF_PCT"]=l11

li=list(df["LF_NU"])
l12=[]
for i in li:
  l12.append(int(i))
df["LF_NU"]=l12

m=list(df["HF"])
l13=[]
for i in m:
  l13.append(int(i))
df["HF"]=l13

n=list(df["HF_PCT"])
l14=[]
for i in n:
  l14.append(int(i))
df["HF_PCT"]=l14

o=list(df["HF_NU"])
l15=[]
for i in o:
  l15.append(int(i))
df["HF_NU"]=l15

p=list(df["TP"])
l16=[]
for i in p:
  l16.append(int(i))
df["TP"]=l16

q=list(df["LF_HF"])
l17=[]
for i in q:
  l17.append(int(i))
df["LF_HF"]=l17

r=list(df["HF_LF"])
l18=[]
for i in r:
  l18.append(int(i))
df["HF_LF"]=l18

s=list(df["sampen"])
l19=[]
for i in s:
  l19.append(int(i))
df["sampen"]=l19

t=list(df["higuci"])
l20=[]
for i in t:
  l20.append(int(i))
df["higuci"]=l20

def apply_results(condition):
            if (condition == 'no stress'):
                return 0  # No Stress
            elif (condition == 'interruption' or condition=="time pressure"):
                return 1  # Stress
            else:
                return 0

df





In [112]:
from sklearn.decomposition import PCA
from sklearn.preprocessing import StandardScaler
df['results'] = df['condition'].apply(apply_results)
x = df.iloc[:,:-2]
y=df.iloc[:,-1]
scaler = StandardScaler()
standardized_features = scaler.fit_transform(x)
pca = PCA(n_components=0.95, random_state=42)
pca_features = pca.fit_transform(standardized_features)
print(y)
df

0       0
1       1
2       0
3       0
4       1
       ..
8329    1
8330    1
8331    1
8332    0
8333    0
Name: results, Length: 8334, dtype: int64


MEAN_RR   MEDIAN_RR  SDRR  RMSSD  SDSD  SDRR_RMSSD  HR      pNN25  \
0         727  727.267280    74     12    12           6  84   4.933333   
1         844  844.407930    58     19    19           3  71  21.000000   
2         966  966.671125   132     21    21           6  63  24.133333   
3         842  842.485905   117     11    11          10  74   4.733333   
4         747  747.941620   143     13    13          10  82   5.933333   
...       ...         ...   ...    ...   ...         ...  ..        ...   
8329      972  972.610110   218     16    16          13  66  11.333333   
8330      756  756.343880    84     23    23           3  79  30.933333   
8331      834  834.000600   115     14    14           7  73   5.933333   
8332      897  897.256430    76     13    13           5  68   7.200000   
8333      834  834.590150   130     18    18           7  77  12.666667   

         pNN50        SD1  ...  HF_PCT  HF_NU    TP  LF_HF  HF_LF  sampen  \
0     0.000000   8.743513  ...       3      9  1698      9      0       2   
1     0.200000  13.650863  ...       1      1  2358     59      0       2   
2     1.800000  15.096571  ...       0      0  4328    129      0       2   
3     0.533333   8.326307  ...       0      3  2854     28      0       2   
4     0.666667   9.447545  ...       0      6  5310     14      0       1   
...        ...        ...  ...     ...    ...   ...    ...    ...     ...   
8329  1.133333  11.737255  ...       0      0  7183    101      0       1   
8330  1.800000  16.447253  ...       2      3  4046     28      0       2   
8331  1.133333  10.592425  ...       0      5  5292     17      0       1   
8332  0.133333   9.530772  ...       0      2  2117     45      0       2   
8333  2.266667  12.935491  ...       3      8  3292     11      0       2   

      higuci  datasetId      condition  results  
0          1        2.0      no stress        0  
1          1        2.0  time pressure        1  
2          1        2.0      no stress        0  
3          1        2.0      no stress        0  
4          1        2.0   interruption        1  
...      ...        ...            ...      ...  
8329       1        2.0  time pressure        1  
8330       1        2.0   interruption        1  
8331       1        2.0  time pressure        1  
8332       1        2.0      no stress        0  
8333       1        1.0              1        0  

[8334 rows x 37 columns]

In [113]:
models = []
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.20)
X_train.shape, X_test.shape, y_train.shape

((6667, 35), (1667, 35), (6667,))

In [114]:
print("Naive Bayes")
from sklearn.naive_bayes import MultinomialNB
NB = MultinomialNB()
NB.fit(X_train, y_train)
predict_nb = NB.predict(X_test)
naivebayes = accuracy_score(y_test, predict_nb) * 100
print(naivebayes)
print(confusion_matrix(y_test, predict_nb))
print(classification_report(y_test, predict_nb))
models.append(('naive_bayes', NB))


Naive Bayes


ValueError: Negative values in data passed to MultinomialNB (input X)

In [115]:
print("SVM")
from sklearn import svm
lin_clf = svm.LinearSVC()
lin_clf.fit(X_train, y_train)
predict_svm = lin_clf.predict(X_test)
svm_acc = accuracy_score(y_test, predict_svm) * 100
print(svm_acc)
print("CLASSIFICATION REPORT")
print(classification_report(y_test, predict_svm))
print("CONFUSION MATRIX")
print(confusion_matrix(y_test, predict_svm))
models.append(('svm', lin_clf))

SVM
55.068986202759454
CLASSIFICATION REPORT
              precision    recall  f1-score   support

           0       0.55      1.00      0.71       903
           1       1.00      0.02      0.04       764

    accuracy                           0.55      1667
   macro avg       0.77      0.51      0.37      1667
weighted avg       0.75      0.55      0.40      1667

CONFUSION MATRIX
[[903   0]
 [749  15]]


/usr/local/lib/python3.10/dist-packages/sklearn/svm/_base.py:1244: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(


In [116]:
print("Logistic Regression")
from sklearn.linear_model import LogisticRegression
reg = LogisticRegression(random_state=0, solver='lbfgs').fit(X_train, y_train)
y_pred = reg.predict(X_test)
print("ACCURACY")
print(accuracy_score(y_test, y_pred) * 100)
print("CLASSIFICATION REPORT")
print(classification_report(y_test, y_pred))
print("CONFUSION MATRIX")
print(confusion_matrix(y_test, y_pred))
models.append(('logistic', reg))

Logistic Regression
ACCURACY
64.12717456508699
CLASSIFICATION REPORT
              precision    recall  f1-score   support

           0       0.65      0.72      0.68       903
           1       0.62      0.55      0.58       764

    accuracy                           0.64      1667
   macro avg       0.64      0.63      0.63      1667
weighted avg       0.64      0.64      0.64      1667

CONFUSION MATRIX
[[648 255]
 [343 421]]


/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


In [117]:
print("Decision Tree Classifier")
dtc = DecisionTreeClassifier()
dtc.fit(X_train, y_train)
dtcpredict = dtc.predict(X_test)
print("ACCURACY")
print(accuracy_score(y_test, dtcpredict) * 100)
print("CLASSIFICATION REPORT")
print(classification_report(y_test, dtcpredict))
print("CONFUSION MATRIX")
print(confusion_matrix(y_test, dtcpredict))

Decision Tree Classifier
ACCURACY
95.68086382723455
CLASSIFICATION REPORT
              precision    recall  f1-score   support

           0       0.97      0.95      0.96       903
           1       0.94      0.97      0.95       764

    accuracy                           0.96      1667
   macro avg       0.96      0.96      0.96      1667
weighted avg       0.96      0.96      0.96      1667

CONFUSION MATRIX
[[854  49]
 [ 23 741]]


In [118]:
print("Convolution Neural Network (CNN)")
from sklearn.neural_network import MLPClassifier
mlpc = MLPClassifier().fit(X_train, y_train)
y_pred = mlpc.predict(X_test)
print("ACCURACY")
print(accuracy_score(y_test, y_pred) * 100)
print("CLASSIFICATION REPORT")
print(classification_report(y_test, y_pred))
print("CONFUSION MATRIX")
print(confusion_matrix(y_test, y_pred))
models.append(('MLPClassifier', mlpc))
detection_accuracy.objects.create(names="Convolution Neural Network (CNN)",ratio=accuracy_score(y_test, y_pred) * 100)



Convolution Neural Network (CNN)
ACCURACY
65.92681463707258
CLASSIFICATION REPORT
              precision    recall  f1-score   support

           0       0.65      0.82      0.72       903
           1       0.69      0.47      0.56       764

    accuracy                           0.66      1667
   macro avg       0.67      0.64      0.64      1667
weighted avg       0.66      0.66      0.65      1667

CONFUSION MATRIX
[[738 165]
 [403 361]]


NameError: name 'detection_accuracy' is not defined